name: explore_map_camera
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  gal: ^2.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_map_camera_location:
    path: packages/flutter_map_camera_location/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
